name: flutter_appsize_generator
description: This package is a simple provider for some IU components.
version: 1.1.0

repository: https://github.com/Auja-Der-Freizeitplaner/flutter_appsize_generator
homepage: https://auja.app/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  analyzer: any
  path: any
  yaml: any

dev_dependencies:
  lints: any
