name: flutter_appsize_generator
description: This package is a simple provider for some IU components.
version: 1.0.0

repository: https://github.com/Auja-Der-Freizeitplaner/flutter_appsize_generator
homepage: https://auja.app/

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  analyzer: ^7.3.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
